spring:
  profiles:
    active: test
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
